language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
before_script:
  - pip install coveralls coverage
script:
  - coverage run --include=grole.py -m unittest discover test
after_success:
  - coveralls
